In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [103]:
df = pd.read_csv('ml2_train.csv')

In [104]:
df.head()

,Serial Number,Main Office,Branch Number,Established Date,Acquired Date,City,County,State,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,1,0,2866,02/06/1910,11/13/2004,Wales,Waukesha,WI,21386.0,23981.0,24825.0,26908.0,30681.0,30680.0,37564
1,2,0,2867,02/28/1910,11/13/2004,Germantown,Washington,WI,55454.0,56564.0,64732.0,73523.0,81357.0,89270.0,106177
2,3,0,2868,05/06/1907,11/13/2004,Brookfield,Waukesha,WI,90882.0,104300.0,125038.0,125906.0,132501.0,137363.0,145054
3,4,0,2869,06/20/1936,11/13/2004,Pewaukee,Waukesha,WI,45674.0,49288.0,53251.0,70402.0,74742.0,73837.0,85996
4,5,0,2870,04/22/1963,11/13/2004,Waukesha,Waukesha,WI,64181.0,72217.0,69920.0,80703.0,75971.0,73225.0,81706

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3790 entries, 0 to 3789
Data columns (total 15 columns):
Serial Number       3790 non-null int64
Main Office         3790 non-null int64
Branch Number       3790 non-null int64
Established Date    3790 non-null object
Acquired Date       2297 non-null object
City                3790 non-null object
County              3790 non-null object
State               3790 non-null object
2010 Deposits       3050 non-null float64
2011 Deposits       3212 non-null float64
2012 Deposits       3461 non-null float64
2013 Deposits       3615 non-null float64
2014 Deposits       3734 non-null float64
2015 Deposits       3771 non-null float64
2016 Deposits       3790 non-null int64
dtypes: float64(6), int64(4), object(5)
memory usage: 444.2+ KB

In [106]:
obj_col = ['State']
df = pd.get_dummies(df, columns=obj_col)

In [107]:
df.drop(['Serial Number','Main Office','Branch Number','County','City','Established Date','Acquired Date'],axis=1,inplace=True)

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3790 entries, 0 to 3789
Data columns (total 32 columns):
2010 Deposits    3050 non-null float64
2011 Deposits    3212 non-null float64
2012 Deposits    3461 non-null float64
2013 Deposits    3615 non-null float64
2014 Deposits    3734 non-null float64
2015 Deposits    3771 non-null float64
2016 Deposits    3790 non-null int64
State_AZ         3790 non-null uint8
State_CA         3790 non-null uint8
State_CO         3790 non-null uint8
State_CT         3790 non-null uint8
State_DC         3790 non-null uint8
State_FL         3790 non-null uint8
State_GA         3790 non-null uint8
State_ID         3790 non-null uint8
State_IL         3790 non-null uint8
State_IN         3790 non-null uint8
State_KY         3790 non-null uint8
State_LA         3790 non-null uint8
State_MA         3790 non-null uint8
State_MI         3790 non-null uint8
State_NJ         3790 non-null uint8
State_NV         3790 non-null uint8
State_NY         3790 non-null uint8
State_OH         3790 non-null uint8
State_OK         3790 non-null uint8
State_OR         3790 non-null uint8
State_PA         3790 non-null uint8
State_TX         3790 non-null uint8
State_UT         3790 non-null uint8
State_WA         3790 non-null uint8
State_WI         3790 non-null uint8
dtypes: float64(6), int64(1), uint8(25)
memory usage: 299.9 KB

In [109]:
X=df.drop('2016 Deposits',axis=1)

In [110]:
y= df['2016 Deposits']

In [111]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

In [112]:
datadm = xgb.DMatrix(data=X,label=y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
xg_reg = xgb.XGBRegressor(objective ='reg:linear')

In [113]:
xg_reg.fit(X_train,y_train)
preds = xg_reg.predict(X_test)

In [114]:
preds

array([  63032.254 ,   48748.875 ,   26321.092 ,   63032.254 ,
         68495.33  ,  119118.92  ,   48748.875 ,   13385.457 ,
        156958.38  ,   40219.16  ,   43130.55  ,   76140.31  ,
        102388.95  ,   34888.29  ,   40219.16  ,   60025.977 ,
         24581.19  ,   34888.29  ,  132556.14  ,   22036.566 ,
         22036.566 ,   53259.23  ,   34888.29  ,   34888.29  ,
         40219.16  ,  102388.95  ,   43130.55  ,   22036.566 ,
         34888.29  ,  129968.8   ,   48748.875 ,   53259.23  ,
         76140.31  ,  102388.95  ,   22036.566 ,  243137.08  ,
        149172.03  ,   92415.14  ,   40219.16  ,   63032.254 ,
         83761.56  ,  102388.95  ,  119118.92  ,   40219.16  ,
         83761.56  ,   35724.56  ,   22036.566 ,   24581.19  ,
         68495.33  ,  349869.62  ,   68495.33  ,  109342.51  ,
         53259.23  ,   53259.23  ,   45235.805 ,   32462.564 ,
         22036.566 ,   29052.742 ,   26321.092 ,   74690.984 ,
         29052.742 ,   49340.04  ,   92415.14  ,   38346.652 ,
         53259.23  ,   68495.33  ,   92415.14  ,  106851.05  ,
         76140.31  ,   83761.56  ,  129968.8   ,  270180.9   ,
         63032.254 ,   48748.875 ,  119118.92  ,   34888.29  ,
        281197.97  ,   30474.01  ,   83761.56  ,   63032.254 ,
         28360.535 ,   13385.457 ,   60025.977 ,   76140.31  ,
         53259.23  ,   83761.56  ,   43130.55  ,  160757.52  ,
         63032.254 ,   60025.977 ,  433833.16  ,   34888.29  ,
        164979.19  ,   53259.23  ,   92415.14  ,   23149.133 ,
        102388.95  ,  106851.05  ,   13385.457 ,   35724.56  ,
         34888.29  ,   86800.75  ,  132556.14  ,   68495.33  ,
         53259.23  ,   34888.29  ,   63032.254 ,   34888.29  ,
         34888.29  ,   53259.23  ,  310232.94  ,   30474.01  ,
         22036.566 ,   60025.977 ,   60025.977 ,   48748.875 ,
         76140.31  ,   68495.33  ,  119118.92  ,   30474.01  ,
        175337.64  ,  216786.78  ,  247358.75  ,  102388.95  ,
        433833.16  ,  177411.92  ,  132556.14  ,   43130.55  ,
         60025.977 ,   48748.875 ,  119118.92  ,   45235.805 ,
         30474.01  ,  102388.95  ,   74690.984 ,   24581.19  ,
        119118.92  ,   53259.23  ,   40219.16  ,  218211.5   ,
         40219.16  ,   43130.55  ,  160757.52  ,  156958.38  ,
         68495.33  ,   43130.55  ,   28360.535 ,   13385.457 ,
         68495.33  ,   22036.566 ,   40219.16  ,  158175.77  ,
         48748.875 ,  132556.14  ,  106851.05  ,  106851.05  ,
         48748.875 ,  310232.94  ,   23149.133 ,   13385.457 ,
         92415.14  ,  119118.92  ,  119118.92  ,   74690.984 ,
         24581.19  ,   83761.56  ,   43130.55  ,  129968.8   ,
        106851.05  ,   22036.566 ,   60025.977 ,   45235.805 ,
         48748.875 ,  149172.03  ,   34888.29  ,   40219.16  ,
        102388.95  ,   40219.16  ,   48748.875 ,  119118.92  ,
         38346.652 ,   43130.55  ,  182141.06  ,  177919.39  ,
         30474.01  ,   22036.566 ,  149172.03  ,  119118.92  ,
         13385.457 ,  119118.92  ,   35724.56  ,  129968.8   ,
         68495.33  ,   49340.04  ,  894302.2   ,   43130.55  ,
         22036.566 ,   76140.31  ,  307861.03  ,   76140.31  ,
         13385.457 ,   28360.535 ,   16309.579 ,   83761.56  ,
         40219.16  ,   43130.55  ,  182141.06  ,  177411.92  ,
         13385.457 ,   60025.977 ,   40219.16  ,  132556.14  ,
        160757.52  ,  102388.95  ,   83761.56  ,  216786.78  ,
        106851.05  ,   34888.29  ,  106851.05  ,   83761.56  ,
         22036.566 ,   76140.31  ,  102388.95  ,   43130.55  ,
        102388.95  ,   34888.29  ,   83761.56  ,   76140.31  ,
        129968.8   ,   87675.56  ,  216786.78  ,  283569.88  ,
         18098.91  ,   53259.23  ,   32462.564 ,   68495.33  ,
         92415.14  ,   49340.04  ,   35724.56  ,   68495.33  ,
         53259.23  ,   34888.29  ,   53259.23  ,   40219.16  ,
        158175.77  ,   48748.875 ,   30474.01  ,  106851.05  ,
         60025.977 ,  106851.05  ,   40219.16  ,   22036.566 ,
         53259.23  ,   60025.977 ,   68495.33  ,  106851.05  ,
         28360.535 ,   32462.564 ,   92415.14  ,  160757.52  ,
         43130.55  ,   13385.457 ,  106851.05  ,   49340.04  ,
        218211.5   ,   34888.29  ,   74690.984 ,   43130.55  ,
         48748.875 ,   40219.16  ,   34888.29  ,   26321.092 ,
         63032.254 ,  106851.05  ,   35724.56  ,   22036.566 ,
         83761.56  ,  129968.8   ,   40219.16  ,   24581.19  ,
         45235.805 ,   48748.875 ,   45235.805 ,  132556.14  ,
         43130.55  ,   60025.977 ,  156958.38  ,   28360.535 ,
         38346.652 ,  182141.06  ,  102388.95  ,   83761.56  ,
        182141.06  ,  102388.95  ,   49340.04  ,   76140.31  ,
        102388.95  ,   74690.984 ,  113852.85  ,  119118.92  ,
        882663.    ,   40219.16  ,   87675.56  ,   34888.29  ,
         53259.23  ,   53259.23  ,  182141.06  ,   76140.31  ,
         87675.56  ,   23149.133 ,   34888.29  ,   30474.01  ,
         68495.33  ,   30474.01  ,   53259.23  ,   40219.16  ,
         30474.01  ,   23149.133 ,  149172.03  ,   43130.55  ,
         60025.977 ,   63032.254 ,   48748.875 ,   23149.133 ,
         30474.01  ,   68495.33  ,   53259.23  ,  391973.78  ,
         22036.566 ,  149172.03  ,   43130.55  ,   38346.652 ,
         53259.23  ,   30474.01  ,  149172.03  ,   76140.31  ,
         49340.04  ,   34888.29  ,   24581.19  ,   23149.133 ,
         28360.535 ,  129968.8   ,  129968.8   ,   60025.977 ,
         18098.91  ,   40219.16  ,   87675.56  ,  119118.92  ,
        102388.95  ,  102388.95  ,   60025.977 ,   34888.29  ,
        119118.92  ,  247358.75  ,   76140.31  ,   74690.984 ,
         63032.254 ,   55404.63  ,   43130.55  ,   13385.457 ,
        207541.84  ,   38346.652 ,   63032.254 ,   76140.31  ,
         40219.16  ,   18098.91  ,   38346.652 ,   34888.29  ,
         40219.16  ,   49340.04  ,   30474.01  ,  158175.77  ,
         92415.14  ,   49340.04  ,   13385.457 ,   83761.56  ,
         40219.16  ,  149172.03  ,   68495.33  ,   18098.91  ,
        119118.92  ,  164979.19  ,   13385.457 ,   63032.254 ,
        106851.05  ,  106851.05  ,  281197.97  ,   92415.14  ,
        324230.5   ,   83761.56  ,   53259.23  ,   60025.977 ,
        310232.94  ,   35724.56  ,   45235.805 ,  265469.06  ,
         30474.01  ,   34888.29  ,   53259.23  ,   43130.55  ,
         63032.254 ,   68495.33  ,   40219.16  ,   60025.977 ,
        247358.75  ,  102388.95  ,   68495.33  ,  119118.92  ,
         22036.566 ,   74690.984 ,  221350.1   ,   60025.977 ,
         49340.04  ,  149172.03  ,   40219.16  ,   48748.875 ,
         83761.56  ,  218211.5   ,  149172.03  ,   53259.23  ,
        106851.05  ,  149172.03  ,  433833.16  ,   29052.742 ,
         38346.652 ,   92415.14  ,  177919.39  ,   83761.56  ,
         76140.31  ,   76140.31  ,  106851.05  ,   76140.31  ,
         35724.56  ,  270180.9   ,  177919.39  ,  160757.52  ,
        324230.5   ,   60025.977 ,  102388.95  ,  106851.05  ,
         40219.16  ,   34888.29  ,   34888.29  ,   63032.254 ,
         40219.16  ,  102388.95  ,   48748.875 ,   60025.977 ,
         24581.19  ,   35724.56  ,   34888.29  ,   43130.55  ,
        106851.05  ,   43130.55  ,  177919.39  ,   30474.01  ,
         40219.16  ,   68495.33  ,  156958.38  ,   34888.29  ,
        159540.12  ,   48748.875 ,   14752.7705,  132556.14  ,
         28360.535 ,   55404.63  ,  177411.92  ,   38346.652 ,
         49340.04  ,   76140.31  ,   53259.23  ,   74690.984 ,
        304667.7   ,   63032.254 ,  216786.78  ,   24581.19  ,
         74690.984 ,   49340.04  ,   92415.14  ,   74690.984 ,
         63032.254 ,   87675.56  ,  132556.14  ,   53259.23  ,
         87675.56  ,   22036.566 ,  177919.39  ,   76140.31  ,
         48748.875 ,   49340.04  ,  149172.03  ,   76140.31  ,
        247358.75  ,   60025.977 ,  119118.92  ,   34888.29  ,
         22036.566 ,   22036.566 ,  129968.8   ,   92415.14  ,
        129968.8   ,   34888.29  ,   53259.23  ,   38346.652 ,
         63032.254 ,   43130.55  ,   92415.14  ,   34888.29  ,
        102388.95  ,  119118.92  ,   49340.04  ,   68495.33  ,
         24581.19  ,   76140.31  ,   76140.31  ,   60025.977 ,
         30474.01  ,   35724.56  ,   60025.977 ,   55404.63  ,
         34888.29  ,   74690.984 ,  136733.94  ,   53259.23  ,
         86800.75  ,   92415.14  ,   60025.977 ,  102388.95  ,
         76140.31  ,   53259.23  ,   53259.23  ,   68495.33  ,
         60025.977 ,  149172.03  ,   60025.977 ,  212565.11  ,
        132556.14  ,  102388.95  ,   68495.33  ,   53259.23  ,
        149172.03  ,  119118.92  ,   34888.29  ,  102388.95  ,
         24581.19  ,   68495.33  ,   53259.23  ,   24581.19  ,
         68495.33  ,   40219.16  ,   34888.29  ,   63032.254 ,
         40219.16  ,  102388.95  ,  182141.06  ,   48748.875 ,
        102388.95  ,  149172.03  ,  283569.88  ,   32462.564 ,
         83761.56  ,   68495.33  ,   22036.566 ,  106851.05  ,
        132556.14  ,   34888.29  ,  177411.92  ,  102388.95  ,
        102388.95  ,   30474.01  ,  119118.92  ,   48748.875 ,
         40219.16  ,  119118.92  ,  119118.92  ,   30474.01  ,
         68495.33  ,   48748.875 ,   63032.254 ,   74690.984 ,
         24581.19  ,   30474.01  ,   40219.16  ,   87675.56  ,
         92415.14  ,  160757.52  ,   68495.33  ,   34888.29  ,
         40219.16  ,   30474.01  ,  162982.55  ,  119118.92  ,
         49340.04  ,   48748.875 ,   86800.75  ,   38346.652 ,
         29052.742 ,   60025.977 ,  119118.92  ,   76140.31  ,
        218211.5   ,   34888.29  ,  159540.12  ,  171705.95  ,
         53259.23  ,   30474.01  ,  182141.06  ,   22036.566 ,
         76140.31  ,   28360.535 ,   49340.04  ,  149172.03  ,
        270180.9   ,  132556.14  ,   23149.133 ,   53259.23  ,
        182141.06  ,   45235.805 , 2041129.8   ,   76140.31  ,
         24581.19  ,   92415.14  ,   24581.19  ,   74690.984 ,
         40219.16  ,   60025.977 ,   35724.56  ,  103657.3   ,
         43130.55  ,   45235.805 ,   83761.56  ,   53259.23  ,
         29052.742 ,   83761.56  ,   30474.01  ,   34888.29  ,
        149172.03  ,   24581.19  ,   34888.29  ,  129968.8   ,
        119118.92  ,   68495.33  ,   53259.23  ,  106851.05  ,
        149172.03  ,   68495.33  ,   43130.55  ,   49340.04  ,
         76140.31  ,   30474.01  ,   48748.875 ,   43130.55  ,
        106851.05  ,  106851.05  ,   43130.55  ,   76140.31  ,
        106851.05  ,  119118.92  ,   34888.29  ,  129968.8   ,
        156958.38  ,   76140.31  ,   63032.254 ,   63032.254 ,
         30474.01  ,   24581.19  ,  177919.39  ,   63032.254 ,
         48748.875 ,  119118.92  ,   38346.652 ,   14752.7705,
         74690.984 ,   60025.977 ,   40219.16  ,  177919.39  ,
         92415.14  ,   22036.566 ,   22036.566 ,  102388.95  ,
         53259.23  ,   18098.91  ,  156958.38  ,   86800.75  ,
         87675.56  ,   76140.31  ,   92415.14  ,   48748.875 ,
        209616.12  ,  106851.05  ,  119118.92  ,   29052.742 ,
        106851.05  ,   28360.535 ,  102388.95  ,   22036.566 ,
        149172.03  ,   63032.254 ,   53259.23  ,   53259.23  ,
         60025.977 ,   48748.875 ,   76140.31  ,  119118.92  ,
         48748.875 ,   34888.29  ,   34888.29  ,   68495.33  ,
         43130.55  ,  247358.75  ,   43130.55  ,   38346.652 ,
         60025.977 ,   45235.805 ,  177919.39  ,   18098.91  ,
        132556.14  ,   60025.977 ,  132556.14  ,   28360.535 ,
         34888.29  ,   83761.56  ,   24581.19  ,   83761.56  ,
         34888.29  ,   45235.805 ,   40219.16  ,  384615.47  ,
         53259.23  ,  102388.95  ,   60025.977 ,  132556.14  ,
         38346.652 ,  106851.05  ,  106851.05  ,   68495.33  ,
         92415.14  ,  106851.05  ,   76140.31  ,  149172.03  ,
        132556.14  ,  119118.92  ,   43130.55  ,   40219.16  ,
         45235.805 ,   74690.984 ,  218211.5   ,   83761.56  ,
         48748.875 ,  207541.84  ,  106851.05  ,   83761.56  ,
         29052.742 ,   74690.984 ,   76140.31  ,   22036.566 ,
        102388.95  ,   34888.29  ], dtype=float32)

In [115]:
y_test

2389     75940
2573     51333
554      19357
2660     69509
533      65360
1845    111970
1970     48331
1189         0
2198    154110
43       37419
879      33040
852      73186
1497     95123
3267     34073
189      66029
2426     62362
257      17046
2950     28177
1915    137488
3691     24546
3571     21526
541      55086
2692     31872
697      28817
3046     39286
1929     97963
1986     41628
2693     17382
3174     35640
746     126264
         ...
3290     58586
2343     86093
2683     68179
1961    124939
1090     37648
1120    113075
1256    100680
1144     93845
1413     88826
1765    101836
2256     80600
1451    117067
1337    131506
1715    121340
3475     53181
2792     41915
2681     45660
15       71102
1711    267168
75       80794
2725     60594
1286    239816
1103    113055
3615     93858
3269     25898
3073     74459
3453     87868
3337     21591
3386     99217
1863     29162
Name: 2016 Deposits, Length: 758, dtype: int64

In [116]:
for i in range(len(preds)):
    if preds[i] == y_test[i]:
        print('Yes')

KeyError: 0

In [117]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 151528.106888