In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('ml2_train.csv')

In [3]:
df.head()

,Serial Number,Main Office,Branch Number,Established Date,Acquired Date,City,County,State,2010 Deposits,2011 Deposits,2012 Deposits,2013 Deposits,2014 Deposits,2015 Deposits,2016 Deposits
0,1,0,2866,02/06/1910,11/13/2004,Wales,Waukesha,WI,21386.0,23981.0,24825.0,26908.0,30681.0,30680.0,37564
1,2,0,2867,02/28/1910,11/13/2004,Germantown,Washington,WI,55454.0,56564.0,64732.0,73523.0,81357.0,89270.0,106177
2,3,0,2868,05/06/1907,11/13/2004,Brookfield,Waukesha,WI,90882.0,104300.0,125038.0,125906.0,132501.0,137363.0,145054
3,4,0,2869,06/20/1936,11/13/2004,Pewaukee,Waukesha,WI,45674.0,49288.0,53251.0,70402.0,74742.0,73837.0,85996
4,5,0,2870,04/22/1963,11/13/2004,Waukesha,Waukesha,WI,64181.0,72217.0,69920.0,80703.0,75971.0,73225.0,81706

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 15 columns):
Serial Number       3772 non-null int64
Main Office         3772 non-null int64
Branch Number       3772 non-null int64
Established Date    3772 non-null object
Acquired Date       2297 non-null object
City                3772 non-null object
County              3772 non-null object
State               3772 non-null object
2010 Deposits       3050 non-null float64
2011 Deposits       3212 non-null float64
2012 Deposits       3461 non-null float64
2013 Deposits       3615 non-null float64
2014 Deposits       3734 non-null float64
2015 Deposits       3771 non-null float64
2016 Deposits       3772 non-null int64
dtypes: float64(6), int64(4), object(5)
memory usage: 442.1+ KB

In [5]:
obj_col = ['State']
df = pd.get_dummies(df, columns=obj_col)

In [6]:
df.drop(['Serial Number','Main Office','Branch Number','County','City','Established Date','Acquired Date'],axis=1,inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 32 columns):
2010 Deposits    3050 non-null float64
2011 Deposits    3212 non-null float64
2012 Deposits    3461 non-null float64
2013 Deposits    3615 non-null float64
2014 Deposits    3734 non-null float64
2015 Deposits    3771 non-null float64
2016 Deposits    3772 non-null int64
State_AZ         3772 non-null uint8
State_CA         3772 non-null uint8
State_CO         3772 non-null uint8
State_CT         3772 non-null uint8
State_DC         3772 non-null uint8
State_FL         3772 non-null uint8
State_GA         3772 non-null uint8
State_ID         3772 non-null uint8
State_IL         3772 non-null uint8
State_IN         3772 non-null uint8
State_KY         3772 non-null uint8
State_LA         3772 non-null uint8
State_MA         3772 non-null uint8
State_MI         3772 non-null uint8
State_NJ         3772 non-null uint8
State_NV         3772 non-null uint8
State_NY         3772 non-null uint8
State_OH         3772 non-null uint8
State_OK         3772 non-null uint8
State_OR         3772 non-null uint8
State_PA         3772 non-null uint8
State_TX         3772 non-null uint8
State_UT         3772 non-null uint8
State_WA         3772 non-null uint8
State_WI         3772 non-null uint8
dtypes: float64(6), int64(1), uint8(25)
memory usage: 298.4 KB

In [8]:
X=df.drop('2016 Deposits',axis=1)

In [9]:
X=X.fillna(0)

In [10]:
y= df['2016 Deposits']

In [11]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

In [12]:
datadm = xgb.DMatrix(data=X,label=y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
xg_reg = xgb.XGBRegressor(objective ='reg:linear',colsample_bytree=0.2,
 learning_rate= 0.01,
 max_depth= 6,
 n_estimators= 9)

In [13]:
from sklearn.model_selection import GridSearchCV

In [ ]:
params={
    'n_estimators':np.arange(0,100,1),
    'max_depth':np.arange(0,10,1),
    'learning_rate':np.arange(0.01,0.25,0.02),
    'colsample_bytree':np.arange(0.1,0.5,0.1)
}
xg_reg = xgb.XGBRegressor(objective ='reg:linear',eval_metric='mae')
gridser = GridSearchCV(xg_reg,params)
gridser.fit(X,y)

In [181]:
gridser.best_params_

{'colsample_bytree': 0.2,
 'learning_rate': 0.01,
 'max_depth': 6,
 'n_estimators': 9}

In [182]:
gridser.best_score_

-0.119825570351281

In [184]:
xg_reg.fit(X_train,y_train)
preds = xg_reg.predict(X_test)

In [185]:
preds

array([11001.299 , 10599.029 ,  7019.7   ,  5481.4956,  7181.4614,
        6829.126 ,  6829.126 ,  6930.4077,  5368.748 ,  5481.4956,
        8438.836 , 10733.868 , 13134.45  ,  8367.33  ,  7019.7   ,
        4690.589 , 18745.508 , 12083.653 , 17397.88  ,  8866.221 ,
       18307.447 ,  6829.126 , 14140.86  ,  5678.236 ,  8866.221 ,
       10733.868 , 13431.283 ,  6829.126 , 17994.666 ,  8866.221 ,
        5481.4956, 12793.23  ,  7720.2344,  5481.4956,  7440.6553,
        8367.33  , 11371.922 ,  8866.221 ,  8866.221 ,  6242.978 ,
        6829.126 ,  4690.589 ,  8866.221 ,  7019.7   ,  8866.221 ,
        6829.126 ,  7103.801 , 10599.029 , 10599.029 ,  8641.84  ,
       15769.072 ,  5481.4956,  9653.669 ,  8367.33  ,  7294.2095,
       13431.283 ,  7221.3447,  8367.33  , 17397.88  , 12793.23  ,
        5683.14  ,  8641.84  , 10599.029 ,  6829.126 ,  8641.84  ,
        6829.126 ,  9268.49  ,  7518.5903,  6604.911 , 13060.66  ,
       11371.922 ,  6829.126 , 23442.    ,  5066.7065,  9675.3545,
        9639.113 , 13060.66  , 28344.79  ,  7518.5903,  6829.126 ,
       10374.648 ,  7720.2344,  9453.043 , 12083.653 ,  6829.126 ,
        7111.914 , 13060.66  ,  6829.126 ,  7440.6553, 28506.629 ,
        5683.14  ,  6829.126 ,  8752.51  , 10599.029 ,  5481.4956,
        6829.126 ,  8866.221 ,  6829.126 ,  6829.126 ,  6604.911 ,
        8641.84  ,  6829.126 ,  9653.669 ,  5132.5586,  5481.4956,
        8641.84  , 13060.66  , 13431.283 ,  5132.5586,  8866.221 ,
       11371.922 ,  7747.041 , 13740.16  ,  8866.221 , 13740.16  ,
       12434.01  ,  9349.165 , 31419.387 ,  6829.126 ,  8866.221 ,
        6829.126 , 18113.21  ,  5481.4956,  6829.126 , 18745.508 ,
        6829.126 ,  5481.4956,  7169.653 , 17397.88  , 10599.029 ,
        8367.33  ,  6829.126 , 11001.299 , 15903.913 , 17397.88  ,
       12083.653 ,  5481.4956,  8836.609 , 10599.029 ,  6604.911 ,
        5957.649 ,  6829.126 ,  6829.126 , 20941.625 ,  6829.126 ,
        6829.126 , 21205.102 , 10024.291 , 13431.283 ,  4690.589 ,
       10599.029 , 10024.291 , 14140.86  ,  6829.126 , 11371.922 ,
        6829.126 , 12484.354 , 25168.969 , 10024.291 , 16877.434 ,
        6829.126 ,  6829.126 ,  7328.0156,  5379.1055, 12083.653 ,
       12793.23  ,  5481.4956,  6829.126 , 16541.965 ,  6829.126 ,
        8866.221 ,  6829.126 ,  6829.126 , 11371.922 ,  7019.7   ,
        6829.126 , 13431.283 ,  5481.4956,  8866.221 ,  6619.9956,
        8493.127 ,  6829.126 , 24038.79  , 10733.868 ,  6829.126 ,
        4690.589 , 25901.594 ,  7328.0156, 13134.45  ,  5368.748 ,
        6829.126 ,  6829.126 ,  8866.221 ,  5481.4956,  9653.669 ,
        8367.33  ,  7221.3447,  8866.221 ,  6829.126 ,  5481.4956,
        5481.4956,  8866.221 ,  8367.33  ,  8367.33  ,  5481.4956,
        6829.126 , 12083.653 ,  7294.2095, 10024.291 ,  6829.126 ,
        8291.482 ,  7328.0156, 12793.23  ,  9609.502 ,  8866.221 ,
        7518.5903,  5066.7065,  5132.5586, 13431.283 , 10024.291 ,
       10895.971 , 11310.761 ,  6829.126 ,  6829.126 ,  8367.33  ,
        6829.126 , 14482.08  , 11371.922 , 10225.936 ,  7019.7   ,
        5683.14  ,  6829.126 ,  5481.4956, 15634.828 , 19342.297 ,
        8367.33  ,  6829.126 ,  5132.5586,  5481.4956, 18904.234 ,
        6641.7676,  6829.126 ,  4690.589 , 18225.062 ,  9675.3545,
        8752.51  ,  7019.7   ,  5683.14  ,  6829.126 ,  6829.126 ,
        6906.9526,  5103.563 ,  6829.126 ,  8866.221 ,  6829.126 ,
       12083.653 , 12658.391 ,  5481.4956,  7328.0156,  6829.126 ,
        5066.7065,  5481.4956, 22094.371 ,  5481.4956,  6499.7627,
        7518.5903,  7294.2095,  6879.42  , 18904.234 ,  8866.221 ,
       10024.291 , 12083.653 ,  9027.018 ,  6604.911 , 17251.543 ,
        7019.7   , 13831.983 ,  8866.221 ,  7440.6553,  9268.49  ,
       11680.799 ,  5481.4956,  6829.126 , 19655.078 ,  8866.221 ,
        8291.482 ,  9911.543 ,  6829.126 ,  8641.84  ,  6829.126 ,
        6829.126 ,  8752.51  , 11371.922 ,  6930.4077,  5481.4956,
       15903.913 ,  8866.221 , 12793.23  , 12444.293 ,  6829.126 ,
        8367.33  ,  7181.4614,  8866.221 ,  8367.33  , 13431.283 ,
        7730.286 ,  8641.84  , 10599.029 ,  6829.126 , 14140.86  ,
       17397.88  ,  8367.33  ,  5481.4956,  7440.6553, 10024.291 ,
        8866.221 , 26516.602 ,  5481.4956, 11371.922 ,  6829.126 ,
       11371.922 ,  8641.84  , 14482.08  ,  8866.221 ,  6829.126 ,
        6829.126 ,  6829.126 ,  5481.4956, 10024.291 , 10599.029 ,
       10024.291 ,  9929.625 ,  6829.126 ,  6829.126 , 13431.283 ,
        6829.126 , 11371.922 ,  8367.33  ,  7103.635 ,  8866.221 ,
        6604.911 ,  8866.221 ,  6829.126 ,  6829.126 ,  9236.844 ,
       11371.922 ,  4690.589 ,  6228.7935,  6829.126 , 12083.653 ,
        7019.7   ,  7720.2344, 12793.23  , 13431.283 , 10024.291 ,
       23751.602 , 12081.499 ,  5481.4956,  8367.33  , 22691.16  ,
        5481.4956,  9675.3545, 10599.029 ,  7019.7   ,  6829.126 ,
       15769.072 , 11734.716 ,  6829.126 , 11371.922 ,  7440.6553,
       10225.936 ,  6829.126 ,  6829.126 ,  8367.33  , 30804.379 ,
       30071.758 ,  6561.172 ,  6829.126 ,  6829.126 ,  8374.576 ,
        6906.9526, 17994.666 ,  8866.221 ,  5683.14  ,  6829.126 ,
       10333.168 , 13431.283 , 13134.45  ,  6829.126 , 10599.029 ,
        8493.127 ,  7495.8535,  8367.33  ,  9639.113 ,  8866.221 ,
        6829.126 ,  7720.2344,  8866.221 , 10599.029 ,  8641.84  ,
        8866.221 , 12434.01  ,  6829.126 ,  6829.126 ,  9236.844 ,
       11371.922 ,  6829.126 ,  6829.126 ,  6829.126 ,  6641.7676,
       10599.029 ,  9944.168 , 13831.983 ,  8245.931 , 16245.133 ,
       17251.543 , 25056.223 ,  5481.4956,  5481.4956,  6829.126 ,
        8866.221 , 10599.029 ,  5368.748 , 13431.283 ,  7518.5903,
        6641.7676,  5481.4956,  8367.33  , 18904.234 ,  8641.84  ,
        6829.126 ,  5368.748 ,  5481.4956,  5481.4956,  6829.126 ,
        8866.221 ,  6829.126 ,  6829.126 ,  5683.14  , 13431.283 ,
        6641.7676,  5683.14  ,  6829.126 ,  6829.126 ,  8367.33  ,
       11371.922 ,  5481.4956,  3342.011 , 10333.168 ,  6829.126 ,
        6829.126 , 10333.168 ,  6829.126 ,  5481.4956,  5481.4956,
       11970.905 , 13431.283 , 17397.88  , 14140.86  ,  7942.5454,
       10024.291 ,  6431.518 ,  6829.126 ,  9675.3545,  5481.4956,
        6829.126 , 11001.299 ,  8245.931 , 10599.029 ,  6829.126 ,
       10599.029 ,  6829.126 ,  7019.7   , 17397.88  ,  5481.4956,
        6829.126 ,  8367.33  ,  8367.33  ,  8866.221 ,  5481.4956,
       10599.029 ,  8367.33  ,  7181.4614,  7294.2095, 11371.922 ,
        8866.221 , 13431.283 ,  7715.1646, 10599.029 , 15634.828 ,
        6829.126 ,  6829.126 , 16245.133 , 10599.029 , 10733.868 ,
        5066.7065,  5481.4956,  3342.011 ,  7019.7   ,  7169.653 ,
       10024.291 ,  5481.4956,  6829.126 , 23751.602 , 10599.029 ,
        8367.33  , 13431.283 ,  5103.563 ,  8866.221 ,  5066.7065,
        8752.51  ,  8612.229 ,  5407.0674,  5481.4956,  8641.84  ,
        9639.113 ,  8866.221 ,  9653.669 , 11371.922 ,  4961.558 ,
        5481.4956,  7720.2344, 13060.66  , 11371.922 ,  5066.7065,
        6906.9526,  7328.0156,  8866.221 ,  6829.126 , 12434.01  ,
       13831.983 , 12083.653 , 10599.029 ,  8367.33  , 19342.297 ,
        5481.4956,  8866.221 , 11371.922 ,  7169.653 , 13831.983 ,
       17592.762 ,  9639.113 , 14140.86  , 14482.08  , 14140.86  ,
        8866.221 , 11001.299 ,  5481.4956, 18307.447 ,  8641.84  ,
       22691.16  ,  6829.126 , 10599.029 ,  6829.126 ,  5481.4956,
       18745.508 ,  5368.748 ,  4690.589 ,  8367.33  ,  5481.4956,
        7169.653 ,  5481.4956, 15903.913 ,  4690.589 ,  7518.5903,
        6829.126 , 11371.922 ,  8866.221 ,  6829.126 ,  5368.748 ,
        8367.33  ,  6829.126 ,  6829.126 , 11371.922 , 77559.35  ,
        6641.7676,  6829.126 ,  5481.4956,  8367.33  , 12159.501 ,
       10599.029 , 12658.391 ,  8866.221 , 15217.104 ,  5481.4956,
       14140.86  , 10024.291 , 13431.283 , 10599.029 , 12484.354 ,
       10024.291 ,  6829.126 , 12658.391 , 11371.922 ,  6829.126 ,
        9639.113 , 11310.761 ,  8866.221 ,  6829.126 ,  8367.33  ,
        6829.126 , 13060.66  ,  5481.4956,  8866.221 ,  6829.126 ,
        8641.84  ,  6906.9526,  8367.33  ,  6829.126 , 11001.299 ,
        5481.4956,  6228.7935,  5481.4956, 10100.139 , 31419.387 ,
       10225.936 ,  8367.33  , 22094.371 , 12658.391 , 11734.716 ,
        6182.03  ,  8367.33  ,  6906.9526, 15903.913 , 17397.88  ,
        9911.543 , 14140.86  , 13431.283 ,  6829.126 ,  7518.5903,
        6829.126 ,  7720.2344,  8866.221 , 12793.23  ,  6829.126 ,
        6829.126 , 27249.223 , 13134.45  , 12658.391 ,  4259.926 ,
       22691.16  , 11371.922 ,  8866.221 ,  8367.33  , 65561.766 ,
        6829.126 , 17397.88  ,  6829.126 ,  7019.7   , 10374.648 ,
        8866.221 ,  6829.126 ,  4893.3135,  8641.84  ,  7720.2344,
        5132.5586,  6829.126 ,  5368.748 , 10374.648 ,  5683.14  ,
        4961.558 ,  7720.2344, 11371.922 , 10024.291 ,  9251.398 ,
       12159.501 , 12793.23  ,  8836.609 ,  7720.2344,  6829.126 ,
        9911.543 ,  8866.221 , 12793.23  ,  8866.221 ,  5368.748 ,
        9855.3125,  5481.4956, 13060.66  ,  7019.7   ,  8866.221 ,
        7518.5903,  7328.0156,  8367.33  ,  8836.609 ,  4690.589 ,
        8367.33  , 12793.23  ,  8367.33  ,  6829.126 ,  8866.221 ,
       20387.129 , 10024.291 , 10599.029 ,  6829.126 ,  6399.4106,
       15002.527 ,  6930.4077, 10024.291 , 11371.922 , 10024.291 ,
        7518.5903,  6829.126 ,  9540.921 ,  8367.33  ,  8577.186 ,
        6829.126 ,  6829.126 ,  8641.84  , 26141.246 , 11371.922 ,
        7169.653 ,  6829.126 , 17994.666 , 13431.283 , 17994.666 ,
        6930.4077,  4880.216 ,  8866.221 , 12793.23  , 13431.283 ,
       25168.969 ,  6604.911 , 12083.653 ,  7294.2095,  5407.0674,
        8866.221 ,  7294.2095, 10225.936 ,  4690.589 ,  7169.653 ,
        5481.4956,  8367.33  , 10100.139 ,  7019.7   ,  6829.126 ,
        5368.748 , 16877.434 , 13431.283 ,  6829.126 , 10024.291 ,
        8866.221 ,  6829.126 ,  7019.7   , 10599.029 ,  6829.126 ,
       16942.666 , 21205.102 , 12484.354 ,  8367.33  ,  5066.7065,
        8641.84  ,  9944.168 ,  8866.221 , 17397.88  ,  6829.126 ],
      dtype=float32)

In [186]:
y_test

967      83931
537      84912
3220     55516
3113     20466
1001     61519
43       37419
3517     40357
2888     70136
2860     45263
3346     47903
3043     95459
1426    100635
1208    172717
2445     53497
3285     47880
2876     18123
1905    222098
1522    129701
1226    219601
2349     49880
1563    246948
2652     11774
319     162568
3029     44086
637      62561
1586    104071
472     141270
2763     27595
1613    206075
1057     35899
         ...
15       71102
2687     52671
75       80794
2883     38963
2237     58972
3038     37746
3112     45021
3456    104272
3150     60588
3241     27968
3079     21621
1317    191352
1411    147237
2297     33672
1309    104699
1445     60583
3493     37737
3060     75182
935      86794
2814     30056
735     196743
1630    226091
2537    167325
2634     49053
2082     35238
698      53812
235     127433
667      87717
1804    210360
315      36266
Name: 2016 Deposits, Length: 755, dtype: int64

In [187]:
from sklearn.metrics import mean_absolute_error
rmse = (mean_absolute_error(y_test, preds))
print("MAE: %f" % (rmse))

MAE: 81131.472088

In [188]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 180140.168546